# Generated by Django 2.2.4 on 2019-09-06 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Retirement', 'Retirement'), ('Vacation', 'Vacation'), ('Savings', 'Savings'), ('Education', 'Education'), ('House', 'House'), ('Investment', 'Investment')], default='Retirement', max_length=100, verbose_name='Portfolio Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('acq_date', models.DateField(default=datetime.date.today)),
                ('unit_cost', models.FloatField(default=1.0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfy.Portfolio')),
            ],
        ),
    ]
