# Generated by Django 2.2.4 on 2019-08-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyfy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='port',
            new_name='portfolio',
        ),
    ]
