# Generated by Django 2.2.4 on 2019-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfy', '0002_auto_20190817_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[('Retirement', 'Retirement'), ('Vacation', 'Vacation'), ('Savings', 'Savings'), ('Education', 'Education'), ('House', 'House'), ('Investment', 'Investment')], default='Retirement', max_length=100, verbose_name='Portfolio Type'),
        ),
    ]
