# Generated by Django 2.2.4 on 2019-08-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfy', '0003_portfolio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='acq_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_cost',
            field=models.IntegerField(default=1),
        ),
    ]
