# Generated by Django 2.2.4 on 2019-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfy', '0004_auto_20190822_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.FloatField(default=1.0),
        ),
    ]
