# Generated by Django 2.2.4 on 2019-08-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfy', '0008_auto_20190822_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='acq_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
